matter-labs/era-compiler-ci

.github/actions/build-llvm/action.yml
Fixes ccache save condition.
Mistakenly merged for debugging purposes before.
=> fix: return save ccache condition back for llvm

.github/workflows/integration-tests.yaml
Set ref parameters `required` to `false`.
It is not always mandatory to specify these parameters.
=> chore: set ref required to false for integration tests

.github/actions/build-llvm/action.yml, .github/workflows/benchmarks.yml, .github/workflows/integration-tests.yaml
=> fix: support custom solc version

.github/workflows/benchmarks.yml
Do not run benchmark analysis if jobs were cancelled
=> fix: skip cancelled jobs in benchmarks analysis

.github/workflows/benchmarks.yml
Disable PR commenting for the benchmark comparison if the workflow is executed from the forked repository.
For security reasons, GitHub restricts fork repositories `GITHUB_TOKEN` in permissions setting it to `read`-only. So, for the fork repository workflows, we will print benchmark comparison to the summary and in logs, but not commenting in the PR.
=> chore: disable PR comment for fork repositories

.github/workflows/integration-tests.yaml
Do not send Slack notification if the workflow is running from the fork repository (external collaborators).
For security reasons, GitHub restricts access to secrets for forks. So, for the fork repository we just report workflow status in Github, but Slack notification will not be sent.
=> chore: disable slack notification sending for forks

.github/workflows/integration-tests.yaml
Use `Linux` label explicitly for the integration tests label.
Try to workaround possible github bug with workflow calls.
=> fix: explicitly use Linux label for integration tests

.github/actions/build-llvm/action.yml
Support different cache for GNU and Musl.
To differentiate between two hashes automatically when GNU Linux is supported now.
=> chore: support different ccache for gnu and musl

.github/actions/build-llvm/action.yml
Add optional `-coverage` suffix for ccache to separate coverage-enabled builds from basic ones and keep both ccaches to speed up workflows.
=> chore: add optional -coverage suffix for ccache

.github/workflows/benchmarks.yml, .github/workflows/integration-tests.yaml
Use upstream solc for EVM target and mode=^ for benchmarks.
=> fix: use upstream solc and mode=^ for EVM target

.github/actions/cargo-check/action.yml
Reduces the time of `cargo checks` jobs in all repositories from ~8 min down to ~1 min.
[Without cache](https://github.com/matter-labs/era-compiler-llvm-context/actions/runs/10387059052) - 8m56s cargo check
[With cache](https://github.com/matter-labs/era-compiler-llvm-context/actions/runs/10387405933/job/28760815978) - 1m11s cargo check
To speed up Rust workflows.
=> feat: support rust gha cache for cargo checks

.github/workflows/benchmarks.yml, .github/workflows/integration-tests.yaml
1. Uses the `--toolchain` parameter rather than a simple switch flag.
2. Rename target to lowercase to match LLVM target triples used to initialize the target machine.
1. Soon we'll have 3 toolchains, so a flag is not enough.
2. Targets shall be named just like in LLVM.
=> feat: use the toolchain enum instead of a flag

.github/actions/cargo-check/action.yml
Save cache when running on `main` and re-use in PRs.
Now, the Rust cargo cache is generated for each PR trashing the repo cache and not re-used across PRs from the main.
This is the first step to proper cache regeneration in repositories.
=> chore: pin rust cargo cache name and save only for main execution

.github/actions/build-llvm/action.yml
Remove `SHORT_SHA` from LLVM ccache entries.
Recently, we switched to `main` in the FE compiler LLVM.lock file. This resulted in the behavior when GH cache entry always had a different name and was unable to be restored. As we're switching to cache regeneration scheduling job, we remove the SHORT_SHA to make cache discoverable by all jobs in PRs.
=> chore: remove short sha from LLVM ccache

.github/workflows/benchmarks.yml, .github/workflows/integration-tests.yaml
We have to prevent a situation when a fork repository `main` branch is not rebased, but some other branch is.
=> fix: use base repo for reference benchmarks and head_ref for tests

.github/actions/build-llvm/action.yml, .github/actions/prepare-msys/action.yml
To fix more python issues. For more info: https://github.com/matter-labs/era-compiler-llvm-builder/pull/41
=> fix: update builder to correctly use python version

.github/actions/build-llvm/action.yml
Adds RTTI and LLVM_PROJECTS support to LLVM build.
To support MLIR builds https://github.com/matter-labs/era-compiler-llvm-builder/pull/37
=> feat: support rtti and different projects for llvm build

.github/workflows/benchmarks.yml
=> fix: separate artifacts for target benchmarks

.github/workflows/benchmarks.yml, .github/workflows/integration-tests.yaml
Fix benchmarks json.
`evm` and `eravm` benchmark results JSONs were mixed up rewriting each other.
=> fix: use unique artifacts json depending on target

.github/actions/rust-unit-tests/action.yml
Execute Rust unit tests in debug mode.
=> fix: execute rust unit tests in debug mode

.github/actions/build-llvm/action.yml
Support multiple LLVM build types.
To extend LLVM build types from debug/release only.
=> feat: support multiple LLVM build types

.github/actions/integration-tests/action.yml, .github/workflows/integration-tests.yaml
Add support for multi-platform integration tests.
To allow running `era-compiler-tester` on MacOS and Windows in addition to Linux.
=> feat: add multi-platform integration tests support

.github/workflows/release-plz.yaml
Add common `crates.io` release workflow.
To be able to release crates to `crates.io` in CI.
=> feat: add common release-plz workflow for crates.io releases

.github/workflows/release-plz.yaml
Change `github_token` to `gh_token` because `github_token` is a reserved name.
=> chore: change github_token to gh_token because its reserved

.github/actions/rust-unit-tests/action.yml
Add self hosted runner into exceptions to save and restore cache due to removal of `cargo` binaries.
https://github.com/Swatinem/rust-cache/issues/16
=> fix: add macos arm64 into exceptions for rust cache

.github/actions/integration-tests/action.yml
Windows support fixes for integration tests.
=> fix: windows support for integration tests

.github/workflows/benchmarks.yml
Use the PR branch in the `analysis` job instead of `main` for benchmarks.
To be able to test updates and fixes in `benchmark-analyzer` in PRs.
=> fix: use pr branch in analysis instead of main

.github/workflows/lnt.yml
Add LNT dev machine support.
To enable LNT PR reports.
=> feat: add LNT dev machine support

.github/workflows/lnt.yml
Fix E+ 0.8 mode in the lnt benchmarking table.
To properly display the MODE in the results for E+.
=> fix: E+ 0.8 mode in the lnt benchmarking table

.github/actions/build-rust/action.yml
Use lld linker on windows only.
`rust-lld` linker is used for Musl targets, and default linker for `gnu` target should be good.
=> fix: use lld linker on windows only

.github/actions/build-solc/action.yml
Always upload solc binary to artifacts.
To remove necessity to update this parameter in CI for all solc branches.
=> chore: always upload solc binary to artifacts

.github/actions/build-rust/action.yml
Use lld on linux for proper static linkage.
Default `ld` cannot properly link libraries linked with `lld`.
https://github.com/matter-labs/solx/actions/runs/14335864552
=> fix: use lld on linux for proper static linkage

.github/workflows/solc-build-release.yml
Use github-hosted stable macos arm64 runner instead of self-hosted machine.
To fix all issues with clone and clean up for era-solidity and other repositories with complex submodules git cloning.
=> chore: use github-hosted stable macos arm64 runner

.github/actions/build-rust/action.yml
Follow-up with https://github.com/matter-labs/era-compiler-ci/pull/69 for the rust builds.
=> fix: use lld linker on windows only during build

.github/actions/build-rust/action.yml, .github/actions/rust-unit-tests/action.yml
To recover `solx` linkage with Boost and solc statically, there is only way to use `lld` for Linux.
The issue with `zksolc` and `zkvyper` linkage can also be fixed by using `lld` natively removing `rust-lld` linker from the config.
=> fix: return -fuse-ld=lld for Rust build and test

.github/actions/rust-unit-tests/action.yml
=> chore: fix typo in rust unit tests

.github/actions/build-solc/action.yml
Use mgw15 suffix for boost on windows.
After packages update on mingw, it's gcc15 now.
=> fix: use mgw15 suffix for boost on windows

.github/actions/build-solc/action.yml, .github/workflows/benchmarks.yml, .github/workflows/integration-tests.yaml
Use prebuilt solc libs and boost for running evm ir-llvm benchmarks and tests.
Tested here: https://github.com/matter-labs/era-solidity/pull/1054
Before, `evm` benchmarks were not correct, because default branch of `solc` was always prebuilt and used during benchmarks.
=> fix: use prebuilt solc running evm ir-llvm benchmarks and tests

.github/workflows/forge-benchmarks.yaml
Remove wrong stderr in sizes json report.
JSON report with build sizes should be used only from stdout, stderr was wrongly added and breaking it in some corner cases where it was not empty.
Redirect `stderr` to /dev/null in this case, because errors and warnings already saved on the previous build step.
=> fix: remove wrong stderr in sizes json report

.github/workflows/forge-benchmarks.yaml
Disables EVM bytecode metadata in Foundry builds.
It messes up with our benchmark stats.
=> fix: disable EVM bytecode metadata in Foundry

.github/workflows/forge-benchmarks.yaml
Disables EVM bytecode metadata in Foundry builds.
It messes up with our benchmark stats.
=> fix: disable EVM bytecode metadata in Foundry [2]

.github/actions/cargo-check/action.yml
Disable `cargo-audit` checks by default.
=> chore: disable cargo audit runs by default
