matter-labs/era-compiler-ci

.github/actions/build-llvm/action.yml, .github/actions/prepare-msys/action.yml, .github/workflows/benchmarks.yml, .github/workflows/integration-tests.yaml
To allow using of common actions in `era-solidity` repository testing and proper forks verification.
=> feat: support custom solc for tests and benchmarks

.github/actions/build-llvm/action.yml
Update llvm builder to 1.0.26.
To support builds with sanitizers enabled.
=> feat: update builder to 1.0.26 with sanitizers support

.github/workflows/benchmarks.yml, .github/workflows/integration-tests.yaml
Use new `zksync-llvm-runner` package from github registry introduced in https://github.com/matter-labs/compiler-infra/pull/84.
To stabilize docker updates.
=> feat: update to new stable docker image

.github/workflows/benchmarks.yml, .github/workflows/integration-tests.yaml
Fix target-machine in solc check.
Overlook from previous patch.
=> fix: make target-machine lowercase in shell checks

.github/actions/build-llvm/action.yml
Add capability to run tests under valgrind.
To be able to find memory violations in LLVM.
=> feat: add capability to run tests under valgrind

.github/actions/build-llvm/action.yml
Update LLVM builder to 1.0.32 to fix Windows tests build issues.
MSYS2 issues with WError fixed in 1.0.32.
=> chore: update llvm builder to 1.0.32

.github/actions/build-llvm/action.yml, .github/actions/prepare-msys/action.yml
* Add proper python support in msys2 environment for correct LLVM tests execution
* Add Boost for `solc` 0.8.27 builds on Windows
=> fix: add proper python in msys2 env, add boost

.github/actions/prepare-msys/action.yml, .github/actions/rust-unit-tests/action.yml
To re-use the same code between our repos.
=> feat: add common rust unit tests action

.github/actions/rust-unit-tests/action.yml
Add Rust unit tests execution in both: release and debug modes.
To catch potential issues in two modes.
=> feat: support release and debug rust unit tests

.github/actions/integration-tests/action.yml, .github/workflows/integration-tests.yaml
Fix Slack notification `jobUrl` link.
The job name was changed which prevented Slack action to create a notification properly.
=> ci: fix slack notifications job url

.github/actions/rust-unit-tests/action.yml
=> fix: correct sanitizers for rust unit tests in debug mode

.github/actions/cargo-check/action.yml
=> chore: update cargo deny action

.github/workflows/release-plz.yaml
Use the correct way to pass secrets to workflow call.
=> chore: use correct way to pass secrets to workflow call

.github/actions/cargo-check/action.yml, .github/actions/rust-unit-tests/action.yml
To fix Rust cache generation in FE compilers repositories.
=> fix: use cargo cache in unit tests action

.github/actions/build-solc/action.yml
Update Boost URL.
The Boost library download URL was changed, update it accordingly to be able to download boost correctly.
=> fix: boost download url for solc builds

.github/workflows/benchmarks.yml
New parameters for benchmarks.
To support `evm` benchmarks with different toolchain and environments.
=> feat: new parameters for benchmarks

.github/workflows/benchmarks.yml
Specify the environment explicitly regardless of the target.
To pass `zk_evm` for `eravm` explicitly.
=> chore: specify environment regardless of the target

.github/workflows/benchmarks.yml, .github/workflows/integration-tests.yaml, .github/workflows/lnt.yml
Add initial LNT workflow.
To upload benchmarking results to LNT.
=> feat: add initial LNT support

.github/workflows/integration-tests.yaml
Fix integration tests runner.
The array is not parsed correctly by GitHub in matrix job resulting in the queue for the unexisting runner.
=> fix: integration tests runner

.github/actions/build-llvm/action.yml
Support additional valgrind options.
Changes to be able to pass `--valgrind-options` from CI.
=> feat: support additional valgrind options

.github/actions/build-solc/action.yml
To be able to build `solc` inside `solx` repository.
=> feat: solc builds updates

.github/actions/build-rust/action.yml, .github/actions/build-solc/action.yml
=> feat: add rust build common action

.github/actions/build-rust/action.yml
=> chore: fix matrix inputs typo

.github/actions/cargo-check/action.yml
Fix another cargo deny check in action.
=> fix: another cargo deny check in action

.github/actions/integration-tests/action.yml, .github/workflows/integration-tests.yaml
Add proper toolchain support for evm integration tests.
Our toolchain is now ready, remove `solc` evm patch added later.
=> fix: add proper toolchain for evm integration tests

.github/actions/integration-tests/action.yml, .github/workflows/benchmarks.yml, .github/workflows/integration-tests.yaml
To unblock solx in tester and across compilers eco.
=> feat: add solx support for benchmarks and int tests

.github/workflows/solc-test.yml
=> Use compiler-tester at era-solidity-test

.github/actions/build-solc/action.yml, .github/actions/prepare-msys/action.yml, .github/workflows/solc-build-release.yml, .github/workflows/solc-test.yml
To have one version of CI for era-solidity repository.
=> feat: add unified solc builds support

.github/actions/build-llvm/action.yml
Use new llvm builder with llvm19 fixes
=> chore: use new llvm builder with llvm19 fixes

.github/workflows/lnt.yml
`solc` version will now be a part of the machine, and tests won't be overridden.
=> fix: update lnt job with latest tester setup

.github/workflows/lnt.yml
Fix modes parsing for LNT results table.
Proper table is here:
https://github.com/matter-labs/era-compiler-llvm/pull/826#issuecomment-2916736902
To properly display results comparison table.
=> fix: lnt modes parsing for results table

.github/actions/prepare-msys/action.yml
Update msys2 packages when installing msys.
Required to get latest cargo and rustc.
=> fix: update msys2 packages when installing msys

.github/workflows/benchmarks.yml, .github/workflows/solc-test.yml
To make sure tests are producing the correct results.
=> chore: fix runners and differences between solc and tester

.github/workflows/benchmarks.yml, .github/workflows/integration-tests.yaml, .github/workflows/lnt.yml
=> chore: support llvm as submodule in tester, remove revm

.github/workflows/forge-benchmarks.yaml, forge-benchmarks/forge-benchmarks.toml, forge-benchmarks/gas.py
To improve the benchmarking ecosystem.
=> feat: update LLVM forge benchmarks

.github/workflows/benchmarks.yml, .github/workflows/forge-benchmarks.yaml
To move to the new reports system.
=> feat: use excel reports for compiler tester
